url: https://cheesesisland.com/
baseurl: /AWDPortfolio

# Site settings
title: Edward Li's Advanced Writing Showcase
email: li.edwa@husky.neu.edu
description: "A website dedicated to showcasing the work I wrote druing ENGW3307(Advanced Writing in the Sciences) during the fall of 2019. "


# Team names, titles and social links
people:
- name: Edward Li
  pic: 1

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/FakeEdwardLi
  - title: facebook
    url: https://www.facebook.com/groups/nuhacks
  - title: github
    url: https://github.com/NEUDitao/


# Build settings
markdown: kramdown
permalink: pretty
